### ISSUE TITLE
Add persistent cache functionality to improve performance

### ISSUE THREAD

**Issue by sanekto** [KarpatkeyDAO/defi-protocols#10]
The idea is that the cache can act as a local database of "answers" from endpoints and/or etherscan, etc.

The implementation must:
* Have two layers of cache, one in ram and one on disk. Disk cache path should be configurable.
* Expose a way to clean the cache. For example using an env variable like `DEFI_PROTO_CLEAN_CACHE=1`
* Be able to be bypassed completely (DEFI_PROTO_CACHE_DISABLE=1)
* Have a way to exclude an argument when used as a decorator. This is because the function may be idempotent even if one argument changes like the web3 client. 
* Have an easy way to replicate/share the cache. This can be handy when running tests so  the CI can download a prepopulated cache.

Example:
```python
@cache(excludes=['web3'])
def get_contract(contract_address, blockchain, web3=None, abi=None, block='latest', index=0):
```

Another way to think about this is in a more declarative way: using an Idempotence marker, and then use that to enable/disable the cache. I like this idea more as it enables the distinction of a cache that the value may change but we want to cache anyway, to things that are always the same if the same arguments (or some of them) are the same.

```python
@idempotent(irrelevant=['web3', 'index', 'block'])
def get_contract(contract_address, blockchain, web3=None, abi=None, block='latest', index=0):
```

**Comment by ph1t0** [comment]
# Progress

- [ ] Aave
- [ ] Agave
- [ ] Aura
- [ ] Azuro
- [ ] Balancer
- [ ] Bancor
- [ ] Compound V2
- [ ] Compound V3
- [ ] Connext
- [ ] Convex
- [ ] Curve
- [ ] Element
- [ ] Elk
- [ ] Honeyswap
- [ ] Idle
- [ ] IronBank
- [ ] Lido
- [ ] Maker
- [ ] mStable
- [ ] Notional
- [ ] QiDao
- [ ] RealT
- [ ] Reflexer
- [ ] SushiSwap
- [ ] Swapr
- [ ] Symmetric
- [ ] UniswapV3
- [ ] Unit
