### ISSUE TITLE
Bug in UniswapV3 

### ISSUE THREAD

**Issue by ph1t0** [KarpatkeyDAO/defi-protocols#129]
`get_fee` function is being call with `decimals=True` by default. So, `underlying` will return an incorrect value when `decimals=False` and `fee=True`:

https://github.com/KarpatkeyDAO/defi-protocols/blob/f58b6256ed93df6189382a7d0dbf13f7ad62ec1a/defi_protocols/UniswapV3.py#L219

@nledo I'm taking care about that in the `test_in_uniswap`  branch but I wanted you to check if my diagnosis is correct.

**Comment by sgzerbo** [comment]
You are right, `get_fee` should also receive the decimals argument inherited from the original call to `underlying:`
`fees = get_fee(nftid, block, blockchain, web3, decimals=decimals) `
