### ISSUE TITLE
Hidden Hand underlying all fix

### ISSUE THREAD

**Issue by sgzerbo** [KarpatkeyDAO/defi-protocols#139]

**Comment by sgzerbo** [comment]
Considering the positions IDs here are aura, balancer, bunni, etc. the underlying_all should return something like this

data = {
    'protocol':'hidden hand',
    'block': 'latest'
    'positions': 
       [ {
             'position ID': 'aura',
             'balances': [
                        {
                            'token': '0x837287326326732t6',
                            'balance': 6262525262,
                        },
                        {
                            'token': '0x837287326326732t6',
                            'balance': 6262525262,
                        }
                    ]
        },
         {
             'position ID': 'balancer',
             'balances': [
                        {
                            'token': '0x837287326326732t6',
                            'balance': 6262525262,
                        },
                        {
                            'token': '0x837287326326732t6',
                            'balance': 6262525262,
                        }
                    ]
        },

**Comment by Richymaestro** [comment]
Because the position_ID is basically now Uri's label I would add some more things so when other people want to also distinguish they can use a better naming. So maybe divide it into:
'position':[
{'protocol' : 'aura'},
{'type':'staking'},
{'address':'0xdaoweihuaejfjeh23089234'},
{'ID':'Uri's ID'}
]
}
