### ISSUE TITLE
Fix Reflexer key error with self.addr

### ISSUE THREAD

**Issue by Richymaestro** [KarpatkeyDAO/defi-protocols#173]
When user is inputting a non-checksummed address the code breaks. This is because it needs a checksummed address to check the blockchain in the DB.
We could checksum the addr first, but for that we need a web3 connection, which needs a blokchain argument. And this blockchain argument is based on the key in the dict with addr key in the DB.
Options we have:
- user should input checksummed address, no code needs to be changed
- user should input blockchain, so the node connection can be made first, and addr can be checksummed
What do you guys think is best? Or maybe other option?

**Comment by ph1t0** [comment]
@Richymaestro We are lowering the input address and all the addresses in the DB: https://github.com/KarpatkeyDAO/defi-protocols/blob/82c98a9d9d9cb6e81d918bee2d37a62f9a8d4705/defi_protocols/Reflexer.py#L28

So, you don't need to instance web3 to check if the address is in the DB.
Then self.addr is checksummed: https://github.com/KarpatkeyDAO/defi-protocols/blob/82c98a9d9d9cb6e81d918bee2d37a62f9a8d4705/defi_protocols/Reflexer.py#L35

**Comment by ph1t0** [comment]
This is the line we have to modify: https://github.com/KarpatkeyDAO/defi-protocols/blob/82c98a9d9d9cb6e81d918bee2d37a62f9a8d4705/defi_protocols/Reflexer.py#L30

**Comment by ph1t0** [comment]
Try this: https://github.com/KarpatkeyDAO/defi-protocols/tree/fix_reflexer_addr_checksum

**Comment by sanekto** [comment]
Hmmm.... I prefer to always have checksummed addresses in databases and in the code itself so we don't have to convert them to checksummed addresses (to minimize the math performed).  
Converting from non checksumed to checksumed does not need a web3 connection, it is only math to convert it:
```
n [1]: from web3 import Web3

In [2]: Web3.to_checksum_address('0xd3cda913deb6f67967b99d67acdfa1712c293601')
Out[2]: '0xd3CdA913deB6f67967B99D67aCDFa1712C293601'
```

**Comment by ph1t0** [comment]
@sanekto: https://github.com/KarpatkeyDAO/defi-protocols/blob/3d7cfdc3ac25577e89b75b5654ae07c796bed83d/defi_protocols/Reflexer.py#L30

**Comment by Richymaestro** [comment]
Hadn't realized we don't need a connection, great!
